# baseURL = "http://rootstalk-2019summer.s3-website-us-east-1.amazonaws.com/"
baseURL = "https://rootstalk.grinnell.edu/"
languageCode = "en-us"
title = "Rootstalk"
theme = "rootstalkzen"
currentIssue = "volume-vi-issue-1"

[menu]

  [[menu.main]]
    identifier = "volume-vi-issue-1"
    name = "Current Issue"
    title = "Volume VI, Issue 1"
    url = "/volume-vi-issue-1/"
    weight = "1"

  [[menu.main]]
    identifier = "rootstalk-archive"
    name = "Archive: the Old Website"
    url = "https://rootstalk-archive.grinnell.edu"
    weight = "2"

  [[menu.main]]
    identifier = "past-issues"
    name = "Past Issues"
    url = "/past-issues/"
    weight = "3"

  [[menu.main]]
    identifier = "about"
    name = "About us"
    url = "/about/"
    weight = "4"

  [[menu.main]]
    identifier = "topics"
    name = "Topics"
    url = "/tags/"
    weight = "5"

  [[menu.main]]
    identifier = "submit"
    name = "Submissions"
    url = "/submit/"
    weight = "6"

[params]
  #sidebar = false
  jquery = true
  newnav = true
  buildDate = '2020-11-12 14:37'
  #copyright = "Rootstalk 2020"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
